### ISSUE TITLE
Usage of .getData() no longer works

### ISSUE THREAD

**Issue by ejwessel** [gnosis/mock-contract#13]
The example given in the README tutorial for [Mocking Methods Individually](https://github.com/gnosis/mock-contract#mocking-methods-individually)
```
token.contract.transferFrom.getData(0, 0, 0)
```
doesn't seen to work. 

The following seems to remedy this.
```
token.contract.methods.transferFrom(0, 0, 0).encodeABI();
```
taken from [here](https://ethereum.stackexchange.com/questions/26234/getdata-is-not-working)

Version Info:
Truffle v5.0.8 (core: 5.0.8)
Solidity - ^0.5.0 (solc-js)
Node v11.12.0
Web3.js v1.0.0-beta.37

**Comment by ejwessel** [comment]
Appears this is being tracked by
https://github.com/gnosis/mock-contract/pull/12

**Comment by fleupold** [comment]
Thanks for reporting and pointing out the open PR related to this. It's merged now.
