### ISSUE TITLE
Can't invoke mocked view functions more than 2 times in a single transaction

### ISSUE THREAD

**Issue by g-r-a-n-t** [gnosis/mock-contract#9]
After upgrading to `Sol 0.5.0`, tests making multiple calls to view functions in a single transaction began failing. I brought this up to @fleupold who determined that it's a gas issue with `updateInvocationCount`

> Turns out that it's a gas issue. https://github.com/gnosis/mock-contract/blob/master/contracts/MockContract.sol#L374 get's forwarded all but 1/64th of the gas and since it throws an exception when called in a view's function context that gas is used. This means there is only very little gas left for the remaining code. Having three of those reverts in a row seems to exceeds the gas limit provided by truffle. The fix would be to change the .call(abi.encodeWithSignature("update... to .call.gas(100000)(abi...

I'll be opening a PR for this shortly with a test that was previously failing.

**Comment by fleupold** [comment]
Credit to @rmeissner who diagnosed the root cause.

**Comment by fleupold** [comment]
Merged and published as [v3.0.6](https://www.npmjs.com/package/@gnosis.pm/mock-contract/v/3.0.6)
